#  SPDX-License-Identifier: Apache-2.0 OR MIT

name: Build
run-name: Continuous integration build and test run

on: [push, workflow_dispatch]

jobs:
  job:
    name: ${{ matrix.triplet }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    concurrency:
      group: ${{ matrix.triplet }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: lukka/get-cmake@latest
      - name: List workspace contents
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
      - name: vcpkg run outputs
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "
      - name: List workspace contents
        run: find $RUNNER_WORKSPACE
        shell: bash
      - name: Cmake configure and build
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'default'
          testPreset: 'default'
      - name: List workspace contents
        run: find $RUNNER_WORKSPACE
        shell: bash
